spring.application.name=groupware
spring.profiles.include=secret
mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mappers/*mapper.xml

# heatwave5
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://10.0.0.59:3306/groupware
#spring.datasource.username=typeofb
#spring.datasource.password=Jordan12!@
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.show-sql=true

# TiDB Cloud
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/groupware?sslMode=trust&enabledTLSProtocols=TLSv1.2,TLSv1.3
#spring.datasource.username=3coSD4HqHuoAwSz.root
#spring.datasource.password=4jvzloNh7WG6JuOH
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.show-sql=true

# Aiven
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://myservice-typeofb.d.aivencloud.com:28429/groupware?sslMode=trust&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1IAz3Uc4aqHit0NNzfg
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.show-sql=true

spring.data.redis.host=redis-16092.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
spring.data.redis.port=16092
spring.data.redis.username=default
spring.data.redis.password=fPWv3OQYyvDOEdzgLebq7D6LfPs18iii

logging.level.com.mjc.groupware=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.security=DEBUG

ffupload.location=${user.home}/upload/groupware/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smtechdev25@gmail.com
spring.mail.password=srrdzxtkmmfhbaln
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

service.key=BAd9O0VP0u%2BZ9Wc3sFeycQ%2F7lsH%2FtwydGYUdhJsV3omES1K69Xh9eLnn7QgRbeYV6MurR%2BgO0y2VdFcSjfedtA%3D%3D

server.servlet.session.persistent=false
server.servlet.session.timeout=24h
